// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZJmLOcJj2FORgR6EwqJYBPq20SFwEZU',
    appId: '1:1003398199249:web:e047962c64b86a5b2052f0',
    messagingSenderId: '1003398199249',
    projectId: 'testing-b89bd',
    authDomain: 'testing-b89bd.firebaseapp.com',
    databaseURL: 'https://testing-b89bd-default-rtdb.firebaseio.com',
    storageBucket: 'testing-b89bd.appspot.com',
    measurementId: 'G-QV221MDMDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4jqMK9gQL92og2YPBmkgYLpAXsdxc4xI',
    appId: '1:1003398199249:android:1f725e2ba14c46f22052f0',
    messagingSenderId: '1003398199249',
    projectId: 'testing-b89bd',
    databaseURL: 'https://testing-b89bd-default-rtdb.firebaseio.com',
    storageBucket: 'testing-b89bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Q8WSi7BXxvHDLM2w8ZBK35Z5Gk81U9U',
    appId: '1:1003398199249:ios:2769e485885fe6d42052f0',
    messagingSenderId: '1003398199249',
    projectId: 'testing-b89bd',
    databaseURL: 'https://testing-b89bd-default-rtdb.firebaseio.com',
    storageBucket: 'testing-b89bd.appspot.com',
    androidClientId: '1003398199249-rt1mjttkbvd43a8hntdaofh7agrbborg.apps.googleusercontent.com',
    iosClientId: '1003398199249-98ojvud8r2gb9dsn4k5hhs77rm91erhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.starterKit',
  );
}
